### ISSUE TITLE
Boost must be integer

### ISSUE THREAD

**Issue by dsandber** [ankane/searchkick#387] opened 2015-02-11 04:02 UTC
The documentation should say that the boost 'field^12' requires an integer.  It seems that 'field^2.5' doesn't work.

**Comment by ankane** [comment] 2015-02-11 04:23
Can you create a failing test case for it?  It appears to work in the test I just added.

**Comment by ankane** [comment] 2015-02-11 04:31
On 2nd look, the test cases for boost don't appear to work as intended, so could still be an issue.

**Comment by dsandber** [comment] 2015-02-11 04:35
I did a gem update and am using Searchkick  0.8.5 -- perhaps it's been fixed afterwards?

Below you can see that the boosts are set to 1 and 10 -- as if I specified shmoo^1 rather than shmoo^1.5.

`
[1] pry(main)> Job.search 'fubar', fields:['shmoo^1.5']
=> #<Searchkick::Results:0x007f999c9142a8
 @klass=Job (call 'Job.connection' to establish a connection),
 @options={:page=>1, :per_page=>100000, :padding=>0, :load=>true, :includes=>nil, :json=>false},
 @response=
  {"took"=>24, "timed_out"=>false, "_shards"=>{"total"=>5, "successful"=>5, "failed"=>0}, "hits"=>{"total"=>0, "max_score"=>nil, "hits"=>[]}}>
[2] pry(main)> Job.search 'fubar', fields:['shmoo^1.5'], execute:false
=> #<Searchkick::Query:0x007f99957eda48
 @body=
  {:query=>
    {:dis_max=>
      {:queries=>
        [{:match=>{"shmoo.analyzed"=>{:query=>"fubar", :operator=>"and", :boost=>10, :analyzer=>"searchkick_search"}}},
         {:match=>{"shmoo.analyzed"=>{:query=>"fubar", :operator=>"and", :boost=>10, :analyzer=>"searchkick_search2"}}},
         {:match=>
           {"shmoo.analyzed"=>{:query=>"fubar", :operator=>"and", :boost=>1, :fuzziness=>1, :max_expansions=>3, :analyzer=>"searchkick_search"}}},
         {:match=>
           {"shmoo.analyzed"=>
             {:query=>"fubar", :operator=>"and", :boost=>1, :fuzziness=>1, :max_expansions=>3, :analyzer=>"searchkick_search2"}}}]}},
   :size=>100000,
   :from=>0,
   :fields=>[]},
 @facet_limits={},
 @klass=Job (call 'Job.connection' to establish a connection),
 @load=true,
 @options={:fields=>["shmoo^1.5"], :execute=>false},
 @padding=0,
 @page=1,
 @per_page=100000,
 @term="fubar">
`

**Comment by ankane** [comment] 2015-02-11 05:26
The code was casting to an integer instead of a float - fixed on master.

**Closed** 2015-02-11 06:08 UTC
