### ISSUE TITLE
match: :phrase does not work with elasticsearch 6

### ISSUE THREAD

**Issue by jeremiahlukus** [ankane/searchkick#1075] opened 2018-02-08 20:46 UTC
I have not changed this code in roughly two months unsure why it is not giving my problems here is my search method in my orders_controler:

```ruby
      def search
         if params[:search] == "inbound" || params[:search] == "Inbound"
           @orders = Order.where.not(inbound_order_id: nil)
         elsif params[:search] == "outbound" || params[:search] == "Outbound"
           @orders = Order.where.not(outbound_order_id: nil)
         elsif params[:search].present?
          @orders = Order.search(params[:search], match: :phrase)
        else
           @orders = Order.all
         end
         @orders = @orders.sort_by(&:created_at).reverse!
         @orders =  @orders.paginate(page: params[:page], per_page: 50)
       end
```

When I put in a search param is throws an error saying `Must specify fields to search`
and highltlights ` @orders = Order.search(params[:search], match: :phrase)` 
the backtrace is : 
```
Completed 500 Internal Server Error in 12ms (ActiveRecord: 2.1ms)



ArgumentError (Must specify fields to search):

app/controllers/stord/orders_controller.rb:15:in `search'
  Rendering /Users/jeremiahparrack/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.5/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout
  Rendering /Users/jeremiahparrack/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.5/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
  Rendered /Users/jeremiahparrack/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.5/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (3.2ms)
  Rendering /Users/jeremiahparrack/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.5/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /Users/jeremiahparrack/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.5/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.6ms)
  Rendering /Users/jeremiahparrack/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.5/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered /Users/jeremiahparrack/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.5/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.7ms)
  Rendered /Users/jeremiahparrack/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.5/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (86.0ms)

```

In my model I have: 

```ruby
searchkick callbacks: :async

 
    def search_data
      attributes.merge(
        company_name: company(&:name),
        facility_name: facility(&:name),
        inbound_order: inbound_order(&:slug),
        outbound_order: outbound_order(&:slug),
         order_items: order_items.map(&:product),
         #order_items: inbound_order.order_items.map(&:product),
         #outbound_order.order_items.map(&:product),
         created_at: created_at.strftime("%d-%m-%Y")
       )
     end
```

Again it works in production I'm unsure why it stopped working locally, it also stopped working on another developer's computer as well.

**Comment by jeremiahlukus** [comment] 2018-02-08 20:53
`Order.search "118", fields: [{id: :exact}]` returns the correct order so it might just be with `match`

**Comment by jeremiahlukus** [comment] 2018-02-08 21:20
```
2.4.1 :038 > Order.search "*"
ArgumentError: Must specify fields to search
	from /Users/jeremiahparrack/.rvm/gems/ruby-2.4.1/gems/searchkick-2.3.2/lib/searchkick/query.rb:520:in `set_fields'
	from /Users/jeremiahparrack/.rvm/gems/ruby-2.4.1/gems/searchkick-2.3.2/lib/searchkick/query.rb:207:in `prepare'
	from /Users/jeremiahparrack/.rvm/gems/ruby-2.4.1/gems/searchkick-2.3.2/lib/searchkick/query.rb:43:in `initialize'
	from /Users/jeremiahparrack/.rvm/gems/ruby-2.4.1/gems/searchkick-2.3.2/lib/searchkick.rb:96:in `new'
	from /Users/jeremiahparrack/.rvm/gems/ruby-2.4.1/gems/searchkick-2.3.2/lib/searchkick.rb:96:in `search'
```

But if i do:
```
Order.search "*", fields: [:_all]
```
It returns all 

and then why i try 
```
Order.search "156", fields: [:_all]
```
It has no hits

**Comment by mikelkew** [comment] 2018-02-09 01:15
It looks like you're using the old 2.3.2 version of Searchkick. This problem was fixed in 2.4.0 so updating your version should fix it.

As for why it occurs locally and not in Production, the most likely reason is that you've updated to Elasticsearch 6 locally (which introduced this problem), but your Production environment is running an older version.

**Comment by jeremiahlukus** [comment] 2018-02-09 14:34
Ok great, it was elastic search. I did update my gem and had the same problem. 

So I downgraded to elasticsearch@5.6 and it works again.

**Comment by jeremiahlukus** [comment] 2018-02-09 14:39
```
{
  "name" : "3Q7XFUT",
  "cluster_name" : "elasticsearch_jeremiahparrack",
  "cluster_uuid" : "5A1csw9JTMSWF10o3LrtcQ",
  "version" : {
    "number" : "6.1.2",
    "build_hash" : "5b1fea5",
    "build_date" : "2018-01-10T02:35:59.208Z",
    "build_snapshot" : false,
    "lucene_version" : "7.1.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

Here was my elasticsearch info. This version does not work with the current version searchkick.

**Comment by ankane** [comment] 2018-02-15 04:33
Cleaning up issues. If you're still having trouble, please check out the contributing guide: https://github.com/ankane/searchkick/blob/master/CONTRIBUTING.md

**Closed by ankane** 2018-02-15 04:33 UTC

**Comment by josephecombs** [comment] 2018-06-04 17:37
I feel like this should be re-opened. I'm having the exact same issue with searchkick 2.5.0 and Elasticsearch 6.2

**Comment by ankane** [comment] 2018-06-04 21:22
@josephecombs please use the gist in the Contributing Guide to reproduce if it’s an issue.
